name: Build Unreal Engine Project

on:
  push:
    branches:
      - 'build'  # Adjust the branch name as needed

jobs:
  build:
    runs-on: windows-latest  # You can choose other OS if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            lfs: true

      - name: Cook, Stage & Package UE Project
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
            RUNUAT_PATH: 'C:/Program Files/Epic Games/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat'
            UPROJECT_PATH: ./DreadedEscape.uproject
            BUILD_CONFIG: Development
            PLATFORM: Win64
            COOK: true
            STAGE: true
            PACKAGE: false
            PAK: false
            SERVER: false
            ARCHIVE: false
            ARCHIVE_PATH: 'C:/Archives/MyGame'
            EDITOR: true
            ENCRYPT_INI: true
            RELEASE: '1.0.0'
            PATCH: '0.9.0'
            MAPS: 'Map1,Map2'